# Week 4 スライド

## NumPy array

In [1]:
#---- sld04/import
import numpy as np

In [2]:
#---- sld04/arange
A = np.arange(24)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
#---- sld04/shape
A.shape

(24,)

In [4]:
#---- sld04/reshape1
A.shape = (3, 8)

In [5]:
#---- sld04/reshape2
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [6]:
#---- sld04/reshape3
A.shape = (2, 3, 4)
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [7]:
#---- sld04/axis-sum
A.shape = (4, 6)
A.sum()            # (4, 6) -> ()
np.sum(A)          # 上と同じ
A.sum(axis=0)      # (4, 6) -> (6,)
np.sum(A, axis=1)  # (4, 6) -> (4,)

array([ 15,  51,  87, 123])

## for

In [8]:
#---- sld04/for-loop1
for i in range(5):
    print(i ** 3)

0
1
8
27
64


## GDP

In [9]:
#---- sld04/gdp-data
price = np.array([[100, 100, 100],
                  [101, 99, 103],
                  [100, 98, 104],
                  [99, 99, 106.]])

quantity = np.array([[1000, 2000, 500],
                     [980, 1980, 510],
                     [1010, 1990, 520],
                     [1005, 2005, 530.]])

In [10]:
#---- sld04/gdp-value
price * quantity

array([[100000., 200000.,  50000.],
       [ 98980., 196020.,  52530.],
       [101000., 195020.,  54080.],
       [ 99495., 198495.,  56180.]])

In [11]:
#---- sld04/gdp-nominal-def/noinc
NGDP = np.sum(price * quantity, axis=1)

In [12]:
#---- sld04/gdp-nominal-show
NGDP

array([350000., 347530., 350100., 354170.])

In [13]:
#---- sld04/gdp-real-no-for
GDP = np.empty(price.shape[0])  # 行数 = 年数

GDP[0] = np.sum(price[0, :] * quantity[0, :])
t = 1
GDP[t] = GDP[t-1] * (np.sum(price[t-1, :] * quantity[t, :]) 
                    / np.sum(price[t-1, :] * quantity[t-1, :]))
t = 2
# .... continue

In [14]:
#---- sld04/gdp-real
T = price.shape[0]  # 行数 = 年数
GDP = np.empty(T)

GDP[0] = np.sum(price[0, :] * quantity[0, :])
for t in range(1, T):
    GDP[t] = (GDP[t-1] 
               * (np.sum(price[t-1, :] * quantity[t, :]) 
                / np.sum(price[t-1, :] * quantity[t-1, :])))

GDP

array([350000.        , 347000.        , 352042.2985066 , 354063.44966341])

In [15]:
#---- sld04/contribution-data
expenditure = np.array(
    [[298.88, 101.56, 132.33, 91.43, -92.62],
     [299.05, 102.28, 139.39, 92.87, -94.62]])

In [16]:
#---- sld04/contribution-diff
diff = np.diff(expenditure, prepend=np.nan, axis=0)
diff

array([[  nan,   nan,   nan,   nan,   nan],
       [ 0.17,  0.72,  7.06,  1.44, -2.  ]])

In [17]:
#---- sld04/contribution-gdp
gdp = expenditure.sum(axis=1)
gdp

array([531.58, 538.97])

In [18]:
#---- sld04/contribution-gdp-shifted
gdp_shift = np.r_[np.nan, gdp[:-1]]
gdp_shift.shape = (2, 1)
gdp_shift

array([[   nan],
       [531.58]])

In [19]:
#---- sld04/contribution
contribution = diff / gdp_shift